from dataclasses import dataclass
from typing import Optional, Union, Tuple
import re


# --------------------------------------------------
# INDEX REPRESENTATION
# --------------------------------------------------
# An index is a tuple (variable_name, integer_offset) denoting the
# arithmetic expression `variable + offset`.  A variable name of "" denotes
# a pure integer constant (e.g. S[3]).  None means "no index" (e.g. RR).

Index = Optional[Tuple[str, int]]


def parse_index(s: str) -> Index:
    """
    Parse an index string.

    Examples
    --------
    't'    -> ('t', 0)
    't-1'  -> ('t', -1)
    't+2'  -> ('t', 2)
    '3'    -> ('', 3)
    ''     -> None
    """
    s = s.strip()
    if not s:
        return None
    if re.fullmatch(r"-?\d+", s):
        return ("", int(s))
    m = re.fullmatch(r"\s*([A-Za-z_][A-Za-z_0-9]*)\s*([+-]\s*\d+)?\s*", s)
    if not m:
        raise ValueError(f"Cannot parse index: {s!r}")
    var = m.group(1)
    off_s = m.group(2)
    off = int(off_s.replace(" ", "")) if off_s else 0
    return (var, off)


def format_index(idx: Index) -> str:
    if idx is None:
        return ""
    var, off = idx
    if var == "":
        return str(off)
    if off == 0:
        return var
    sign = "+" if off > 0 else ""
    return f"{var}{sign}{off}"


# --------------------------------------------------
# CATEGORY
# --------------------------------------------------

@dataclass(frozen=True)
class Category:
    """
    A CCG category represented as a binary tree.  Atomic categories may
    optionally carry an index (variable, offset).

    Atomic:
        Category("S")                              -> S
        Category("S", index=("t",  0))             -> S[t]
        Category("S", index=("t", -1))             -> S[t-1]
        Category("RR")                             -> RR

    Complex:
        Category("S", "\\", Category("RR"))        -> S\\RR
        Category(Category("S", index=("t",  0)),
                 "\\",
                 Category("S", index=("t", -1)))   -> S[t]\\S[t-1]

    Equality (auto-generated by @dataclass) takes the index into account,
    so S[t] != S[t-1] and S[t] != S.  This is what the combinators in
    parser.py rely on.
    """

    result: Union[str, "Category"]
    slash: Optional[str] = None
    argument: Optional["Category"] = None
    index: Index = None  # only meaningful when atomic

    def is_atomic(self) -> bool:
        return self.slash is None

    def __str__(self) -> str:
        if self.is_atomic():
            base = str(self.result)
            if self.index is not None:
                return f"{base}[{format_index(self.index)}]"
            return base
        left = str(self.result)
        if isinstance(self.result, Category) and not self.result.is_atomic():
            left = f"({left})"
        right = str(self.argument)
        if not self.argument.is_atomic():
            right = f"({right})"
        return f"{left}{self.slash}{right}"

    # --------------------------------------------------
    # Index manipulation
    # --------------------------------------------------

    def free_variables(self) -> set:
        """Set of index-variable names appearing anywhere in this category."""
        if self.is_atomic():
            if self.index is not None and self.index[0]:
                return {self.index[0]}
            return set()
        out = set()
        if isinstance(self.result, Category):
            out |= self.result.free_variables()
        out |= self.argument.free_variables()
        return out

    def substitute(self, var: str, new_var: str, shift: int) -> "Category":
        """
        Replace every atomic index (var, k) with (new_var, shift + k).

        Used by the parser to instantiate a lexical scheme: given the
        scheme  (S[t] \\ S[t-1]) \\ RR  and the input token  g[t-1],  the
        scheme variable `t` is substituted by  (`t`, shift = -1),  yielding
        (S[t-1] \\ S[t-2]) \\ RR.
        """
        if self.is_atomic():
            if self.index is not None and self.index[0] == var:
                return Category(self.result,
                                index=(new_var, shift + self.index[1]))
            return self
        new_result = (self.result.substitute(var, new_var, shift)
                      if isinstance(self.result, Category) else self.result)
        new_arg = self.argument.substitute(var, new_var, shift)
        return Category(new_result, self.slash, new_arg)

    def head_name(self) -> str:
        """Innermost result name after unwinding all slashes.  S[t]\\S[t-2]
        has head_name 'S'; RR\\RR has head_name 'RR'."""
        cat = self
        while not cat.is_atomic():
            cat = cat.result if isinstance(cat.result, Category) else Category(cat.result)
        return cat.result


# --------------------------------------------------
# CATEGORY STRING PARSER
# --------------------------------------------------

def parse_category(s: str) -> Category:
    r"""
    Parse a category from a string.  Slashes are left-associative
    (X/Y\Z is (X/Y)\Z), matching the convention in Steedman (2000).

    Examples
    --------
    parse_category("RR")                  -> Category("RR")
    parse_category("S[t]")                -> Category("S", index=("t", 0))
    parse_category(r"RR\RR")              -> Category(Category("RR"), "\\", Category("RR"))
    parse_category(r"(S[t]\S[t-1])\RR")   -> ((S[t] \ S[t-1]) \ RR)
    """
    s = s.replace(" ", "")
    pos = [0]

    def peek():
        return s[pos[0]] if pos[0] < len(s) else None

    def consume(c=None):
        if c is not None and peek() != c:
            raise ValueError(f"Expected {c!r} at {pos[0]} in {s!r}")
        ch = s[pos[0]]
        pos[0] += 1
        return ch

    def parse_atom():
        m = re.match(r"[A-Za-z_][A-Za-z_0-9]*", s[pos[0]:])
        if not m:
            raise ValueError(f"Expected atom at {pos[0]} in {s!r}")
        name = m.group(0)
        pos[0] += len(name)
        idx = None
        if peek() == "[":
            consume("[")
            end = s.index("]", pos[0])
            idx = parse_index(s[pos[0]:end])
            pos[0] = end
            consume("]")
        return Category(name, index=idx)

    def parse_primary():
        if peek() == "(":
            consume("(")
            cat = parse_cat()
            consume(")")
            return cat
        return parse_atom()

    def parse_cat():
        left = parse_primary()
        while peek() in ("/", "\\"):
            sl = consume()
            right = parse_primary()
            left = Category(left, sl, right)
        return left

    cat = parse_cat()
    if pos[0] != len(s):
        raise ValueError(f"Trailing input at {pos[0]} in {s!r}")
    return cat
